package crewai

import "context"

// Role identifies the author of a message in a conversation with the model.
type Role string

const (
	// RoleSystem contains the system instructions (persona/rules) of the agent.
	RoleSystem Role = "system"
	// RoleUser represents the user's input (the task to be performed).
	RoleUser Role = "user"
	// RoleAssistant represents the response generated by the model.
	RoleAssistant Role = "assistant"
	// RoleTool represents the result of a tool execution.
	RoleTool Role = "tool"
)

// Message is a single message exchanged with the language model.
type Message struct {
	Role    Role   `json:"role"`
	Content string `json:"content"`
}

// LLM is the minimal abstraction that any language model provider must
// implement to be used by agents.
//
// The implementation must be safe for concurrent use, since the same LLM can
// be shared by several agents running in parallel.
type LLM interface {
	// Call sends the conversation to the model and returns the generated text.
	Call(ctx context.Context, messages []Message) (string, error)
	// Model returns the model identifier (e.g. "gpt-4o-mini").
	Model() string
}

// SystemMessage is a shortcut to create a system message.
func SystemMessage(content string) Message {
	return Message{Role: RoleSystem, Content: content}
}

// UserMessage is a shortcut to create a user message.
func UserMessage(content string) Message {
	return Message{Role: RoleUser, Content: content}
}

// AssistantMessage is a shortcut to create an assistant message.
func AssistantMessage(content string) Message {
	return Message{Role: RoleAssistant, Content: content}
}
